# Generated by Django 5.2.10 on 2026-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('text', models.CharField()),
                ('comments', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
