# Generated by Django 5.2.10 on 2026-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Без категории'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.CharField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.CharField(default='Нет данных'),
        ),
    ]
