# Generated by Django 5.2.10 on 2026-01-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category_post_created_at_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('text', models.CharField()),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
