# Generated by Django 5.2.10 on 2026-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fio',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default=''),
        ),
    ]
