# Generated by Django 5.2.10 on 2026-01-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_post_id_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.CharField(default='Нет данных'),
        ),
    ]
